[package]
name = "lsw"
version = "0.1.0"
authors = ["Chase Wilson <me@chasewilson.dev>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
llvm-sys = "100.1.1"
static_assertions = "1.1.0"

[dev-dependencies]
tempfile = "3.1.0"
